"""add user table

Revision ID: 1e9afbfe0b1e
Revises: e3c2994096da
Create Date: 2026-06-23 14:47:53.216785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel              # SQLModel 컬럼 타입(AutoString 등)이 생성된 마이그레이션에서 필요


# revision identifiers, used by Alembic.
revision: str = '1e9afbfe0b1e'
down_revision: Union[str, Sequence[str], None] = 'e3c2994096da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
