"""add item stock

Revision ID: 33de7dc7f218
Revises: fee64d19639c
Create Date: 2026-07-09 10:18:47.489168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel              # SQLModel 컬럼 타입(AutoString 등)이 생성된 마이그레이션에서 필요


# revision identifiers, used by Alembic.
revision: str = '33de7dc7f218'
down_revision: Union[str, Sequence[str], None] = 'fee64d19639c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'stock')
    # ### end Alembic commands ###
