"""create item table

Revision ID: c2d0d177da1c
Revises: 
Create Date: 2026-06-23 11:25:12.097442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel              # SQLModel 컬럼 타입(AutoString 등)이 생성된 마이그레이션에서 필요


# revision identifiers, used by Alembic.
revision: str = 'c2d0d177da1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
