"""뭘 바꿨는지

Revision ID: e3c2994096da
Revises: c2d0d177da1c
Create Date: 2026-06-23 11:32:50.068134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel              # SQLModel 컬럼 타입(AutoString 등)이 생성된 마이그레이션에서 필요


# revision identifiers, used by Alembic.
revision: str = 'e3c2994096da'
down_revision: Union[str, Sequence[str], None] = 'c2d0d177da1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
