"""add item owner

Revision ID: fee64d19639c
Revises: 1e9afbfe0b1e
Create Date: 2026-06-29 10:17:26.312963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel              # SQLModel 컬럼 타입(AutoString 등)이 생성된 마이그레이션에서 필요


# revision identifiers, used by Alembic.
revision: str = 'fee64d19639c'
down_revision: Union[str, Sequence[str], None] = '1e9afbfe0b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user_id')
    # ### end Alembic commands ###
